#!/usr/bin/env bash
# For our imaginary mercurial plugin, triggers a rebuild

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; REV="$2"
SLACK_PATH=$PLUGIN_PATH/slack
sh $SLACK_PATH/slack -r "${SLACK_CHANNEL}" -u Deployer -m "Create Codebase for ${APP} with revision ${REV}" -t "Deploy Begins" -c "#ebebeb";
